name: Golang Format

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  gofmt:
    name: Golang Format
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Check Go formatting
        run: |
          if [ -n "$(go fmt ./...)" ]; then
            echo "Go files must be formatted with gofmt. Please run 'go fmt ./...' and commit the changes."
            exit 1
          fi
