name: Golang Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  gotest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run tests with coverage
        run: |
          go test -v -count 3 -race -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.out